manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: e108e319c0326a3d29862f44fe51fb87d6dd6855
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      
  self:
    path: config
