manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 75c9d5f6fd79745203a15b7bc486ceccb4ef80cf
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      
  self:
    path: config
