manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: ff9d3269399f400a89819259ed58a0e868e99126
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      
  self:
    path: config
